name: 'PR Validation - Auto Triggered'

on:
  pull_request:
    types: [opened, synchronize, reopened, created, ready_for_review, labeled]
    branches:
      - develop1
    paths:
      - 'src/**'
  
  workflow_dispatch:
  

jobs:
  Validate_Changes_on_STR6:
    name: 'Validate Changes on develop1'
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'develop'
    env:
        SALESFORCE_ENV_NAME: develop1
    
    #environment:
    #    name: main
        
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
            
      - name: Install stable Version of SFDX CLI
        run: npm install -g  sfdx-cli

      - name: 'Installing sfdx git delta to Generate Changed Files'
        run: echo y | sfdx plugins:install sfdx-git-delta

      - name: 'Authenticate develop Org'
        run: |
          echo "${{ secrets.develop_SFDX_AUTH_URL }}" > ./authfile
          sfdx auth:sfdxurl:store -f authfile -a $SALESFORCE_ENV_NAME
            
      - name: '--- Please wait!!! Running Validate Only on your added and modified metadata on main package to STR6 Org'
        run: |
              echo "---- Validate added and modified metadata on main package with RunSpecifiedTests----"
              sfdx force:source:deploy -p src/main/default  -u $SALESFORCE_ENV_NAME --checkonly -w 30
        shell: bash  
